In [2]:
import control as cn
import slycot as sc
import numpy as np
import Algorithms as alg

In [3]:
NUM = [[[1], [0]],[[0], [1]]]
DEN = [[[10, 1.], [100,1.]],[[1.], [10,1.]]]
G = cn.tf(NUM,DEN)
# Step response for 100 s ( in 100 steps), initial conditions, Input, Output
y, t = cn.matlab.step(G,None,0.0, 1,1)
# Get the response data
y[:]
# Get the gain of the Matrix at Frequency 
mag,phase,omega = cn.freqresp(G,[0])
# Perform svd
u,s,d = np.linalg.svd(np.mat(mag))
y

array([ 0.        ,  0.06826522,  0.13187029,  0.19113335,  0.24635081,
        0.29779883,  0.34573475,  0.39039831,  0.4320129 ,  0.47078666,
        0.50691352,  0.54057418,  0.57193698,  0.60115879,  0.62838577,
        0.6537541 ,  0.67739065,  0.69941365,  0.71993324,  0.73905206,
        0.75686572,  0.77346334,  0.78892791,  0.80333679,  0.81676205,
        0.82927083,  0.84092569,  0.85178493,  0.86190287,  0.8713301 ,
        0.88011378,  0.88829784,  0.89592321,  0.90302803,  0.90964784,
        0.91581575,  0.92156261,  0.92691715,  0.93190617,  0.93655461,
        0.94088572,  0.94492117,  0.94868114,  0.95218443,  0.95544857,
        0.95848989,  0.96132358,  0.96396384,  0.96642385,  0.96871594,
        0.97085155,  0.97284138,  0.97469536,  0.97642279,  0.97803229,
        0.97953192,  0.98092918,  0.98223106,  0.98344406,  0.98457425,
        0.98562729,  0.98660845,  0.98752263,  0.9883744 ,  0.98916802,
        0.98990747,  0.99059644,  0.99123837,  0.99183649,  0.99

In [4]:
# PI Controller
pi = cn.tf([0.1],[0.1])+cn.tf([1],[1,0])
# Convert
pi = cn.tf2ss(pi)
# Append -> MIMO Controller
pi_mimo = cn.bdalg.append(pi,pi)
pi_mimo

A = [[-0.  0.]
 [ 0. -0.]]

B = [[ 1.  0.]
 [ 0.  1.]]

C = [[ 1.  0.]
 [ 0.  1.]]

D = [[ 1.  0.]
 [ 0.  1.]]

In [5]:
# Make a feedback sys
A = np.zeros((2,2))
B = A
C = A
D = np.eye(2)
fb = cn.ss(A,B,C,D)
# Connect for 2DOF controller
cn.feedback(cn.tf2ss(G),pi_mimo)*pi_mimo
# Connect for 1 DOF controller
CL = cn.feedback(cn.tf2ss(G)*pi_mimo,fb)
CL2 = cn.ss2tf(cn.feedback(cn.tf2ss(G)*pi_mimo,fb))
CL3 = cn.matlab.balred(CL,2)

In [6]:
CL

A = [[ 0.   0.   0.  -1. ]
 [ 0.   0.  -1.   0. ]
 [ 0.   0.1 -0.2  0. ]
 [ 0.1  0.   0.  -0.2]]

B = [[ 1.   0. ]
 [ 0.   1. ]
 [ 0.   0.1]
 [ 0.1  0. ]]

C = [[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]]

D = [[ 0.  0.]
 [ 0.  0.]]

In [7]:
CL3

A = [[ -1.00000000e-01   7.49695295e-19]
 [ -8.97847097e-19  -1.00000000e-01]]

B = [[  4.56195005e-01   2.53357490e-19]
 [  1.19122669e-20  -4.56195005e-01]]

C = [[  4.56195005e-01  -5.88425892e-19]
 [ -9.72148372e-19  -4.56195005e-01]]

D = [[ 0.  0.]
 [ 0.  0.]]

In [ ]:
y, t = cn.matlab.step(C,None,0.0, 1,1)
