In [1]:
import Algorithms as alg
import numpy as np
import pandas as pd

In [6]:
File = open('PhysicalIdentification.csv')
Data = pd.DataFrame.from_csv(File, sep =';')

In [62]:
for i in range(5):
    K = Data.loc[i][2:6]
    K = np.reshape(K.values,(2,2))
    T = Data.loc[i][6:10]
    T = np.reshape(T.values,(2,2))
    L = Data.loc[i][10:14]
    L = np.reshape(L.values,(2,2))
    KD = np.diag(np.diag(K))
    KA = K-KD
    S = -np.dot(np.linalg.inv(KD),KA)
    E = np.dot((np.dot(K,np.eye(2)+S)-KD), np.linalg.inv(KD))
    print("Pairing")
    #print(E)
    print(np.linalg.svd(E,compute_uv=False))
    KD = np.diag(K[[0,1],np.argmax(alg.RGA(K,T,L),axis=0)])
    KA = K-KD
    S = -np.dot(np.linalg.inv(KD),KA)
    print("Sensitivity Gain")
    print(np.linalg.svd(np.linalg.inv(np.eye(2)-np.dot(S,S)), compute_uv=False))
    E = np.dot((np.dot(K,np.eye(2)+S)-KD), np.linalg.inv(KD))
    print("RGA")
    print(np.argmax(alg.RGA(K,T,L),axis=0))
    #print(E)
    print(np.linalg.svd(E,compute_uv=False))
    

Pairing
[ 0.8583335  0.8583335]
Sensitivity Gain
[ 0.53811654  0.53811654]
RGA
[0 1]
[ 0.8583335  0.8583335]
Pairing
[ 1.86539548  1.86539548]
Sensitivity Gain
[ 0.8001488   0.30341505]
RGA
[1 0]
[ 6.49503373  1.48799628]
Pairing
[ 1.91241458  1.91241458]
Sensitivity Gain
[ 0.75022652  0.39016498]
RGA
[1 0]
[ 4.00539379  2.07527036]
Pairing
[ 1.40433109  1.40433109]
Sensitivity Gain
[ 0.78608332  0.21559794]
RGA
[1 0]
[ 5.99625224  2.13647878]
Pairing
[ 0.90134797  0.90134797]
Sensitivity Gain
[ 0.52594266  0.52594266]
RGA
[0 1]
[ 0.90134797  0.90134797]


In [50]:
K[[0,1],np.argmax(alg.RGA(K,T,L),axis=0)]

array([-0.78593021, -5.92262714])

In [56]:
G = np.array([[2,(-5+5*1j)],[5,10]])/(1j+1)
np.multiply(G,np.linalg.inv(np.transpose(G)))

array([[ 0.33962264+0.18867925j,  0.66037736-0.18867925j],
       [ 0.66037736-0.18867925j,  0.33962264+0.18867925j]])

In [57]:
np.linalg.inv(np.transpose(G))

array([[ 0.07547170+0.26415094j, -0.03773585-0.13207547j],
       [ 0.16981132+0.09433962j,  0.01509434+0.05283019j]])

In [61]:
np.argmax(G, axis=1), np.max(G,axis=1)

(array([0, 1]), array([ 1.-1.j,  5.-5.j]))

In [67]:
A = np.array([[2,-1],[5,10]])
Ainv=np.linalg.inv(A)

In [68]:
B = np.array([[1.05,-.05],[.05,1.05]])
APinv=np.linalg.inv(np.dot(B,A))

In [69]:
APinv

array([[ 0.37828054,  0.0561086 ],
       [-0.19366516,  0.06696833]])

In [70]:
np.dot(APinv,A)

array([[ 1.03710407,  0.18280543],
       [-0.05248869,  0.86334842]])

In [71]:
np.dot(B,A)

array([[  1.85,  -1.55],
       [  5.35,  10.45]])