In [1]:
import Algorithms_Graphic as alg
import control as cn
import numpy as np

In [19]:
K = np.array([[1,5],[0.5,1]])
T = np.array([[50,25],[10,17]])
L = np.array([[7,5],[2,3]])
np.linalg.inv(K),K

(array([[-0.66666667,  3.33333333],
        [ 0.33333333, -0.66666667]]), array([[ 1. ,  5. ],
        [ 0.5,  1. ]]))

In [20]:
alg.Control_Astrom(K,T,L, 0.1*np.eye(2),graphics = 'on')

(array([[ 1.,  0.],
       [ 0.,  1.]]), array([[  5.        ,  90.        ],
       [  2.66666667,   3.66666667]]), array([[7, 0],
       [0, 3]]))


(array([[[ 0.22638889,  0.04241831,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],
 
        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]]]), array([[ 1.,  0.],
        [ 0.,  1.]]), array([[-0.66666667,  3.33333333],
        [ 0.33333333, -0.66666667]]))

In [4]:
np.multiply(np.linalg.inv(K),K)

array([[-0.33333333,  1.33333333],
       [ 1.33333333, -0.33333333]])