In [1]:
import numpy as np
import Algorithms as alg

In [12]:
G = 1./(1j+1)*np.array([[2, 5*1j-1],[5, 10]])
GInv = np.linalg.inv(G)
np.multiply(G,np.transpose(GInv))

array([[ 0.4+0.4j,  0.6-0.4j],
       [ 0.6-0.4j,  0.4+0.4j]])

In [11]:
GInv

array([[-0.0+0.4j ,  0.2+0.04j],
       [ 0.0-0.2j ,  0.0+0.08j]])

In [30]:
D = np.array([[1.05, -0.01],[0.01,1.05]])
G = np.array([[2,-1],[5,10]])
np.dot(np.linalg.inv(np.dot(D,G)),G)

array([[ 0.96970796,  0.03664067],
       [-0.01052059,  0.93488119]])

In [31]:
np.dot(D,G)/G

array([[ 1.025,  1.15 ],
       [ 1.054,  1.049]])