In [2]:
import Algorithms as alg
import numpy as np

In [51]:
K = np.array([[1,1.2],[4.166,5]])
T = np.array([[0,0],[0,0]])
L = np.array([[0,0],[0,0]])

In [52]:
KD = np.diag(np.diagonal(K))
E = np.dot(K-KD, np.linalg.inv(KD))
np.dot(E,E),np.linalg.svd(E, compute_uv = False)


(array([[ 0.99984,  0.     ],
        [ 0.     ,  0.99984]]), array([ 4.166,  0.24 ]))

In [25]:
E = -np.dot(np.dot((K-KD),np.linalg.inv(KD)),np.dot((K-KD),np.linalg.inv(KD)))
E,np.linalg.svd(E, compute_uv = False)

(array([[-0.24, -0.  ],
        [-0.  , -0.24]]), array([ 0.24,  0.24]))

In [56]:
G = np.array([[2,(-5+5*1j)],[5,10]])/(1j+1)
np.multiply(G,np.linalg.inv(np.transpose(G)))

array([[ 0.33962264+0.18867925j,  0.66037736-0.18867925j],
       [ 0.66037736-0.18867925j,  0.33962264+0.18867925j]])

In [57]:
np.linalg.inv(np.transpose(G))

array([[ 0.07547170+0.26415094j, -0.03773585-0.13207547j],
       [ 0.16981132+0.09433962j,  0.01509434+0.05283019j]])

In [61]:
np.argmax(G, axis=1), np.max(G,axis=1)

(array([0, 1]), array([ 1.-1.j,  5.-5.j]))

In [67]:
A = np.array([[2,-1],[5,10]])
Ainv=np.linalg.inv(A)

In [68]:
B = np.array([[1.05,-.05],[.05,1.05]])
APinv=np.linalg.inv(np.dot(B,A))

In [69]:
APinv

array([[ 0.37828054,  0.0561086 ],
       [-0.19366516,  0.06696833]])

In [70]:
np.dot(APinv,A)

array([[ 1.03710407,  0.18280543],
       [-0.05248869,  0.86334842]])

In [71]:
np.dot(B,A)

array([[  1.85,  -1.55],
       [  5.35,  10.45]])